export const heroSectionHeight = 400

export const bookData = {
  title: "Harry Potter and the Philosopher's Stone",
  author: 'J.K. Rowling',
  coverUrl: '/book.png',
  publishYear: '1997',
  rating: 4.5,
  ratingsCount: 126543,
  description: 'Harry Potter has never even heard of Hogwarts...',
  subjects: [
    'Fantasy',
    'Young Adult',
    'Magic',
    'Adventure',
    'School',
    'Friendship',
  ],
  details: {
    isbn: ['9780747532699', '0747532699'],
    publisher: 'Bloomsbury Publishing',
    publishDate: 'June 26, 1997',
    pages: 223,
    language: 'English',
    format: 'Hardcover',
    weight: '340g',
    dimensions: '19.6 x 12.8 x 2.2 cm',
  },
  authorBio: 'J.K. Rowling is the author of the seven Harry Potter books...',
  reviews: [
    {
      id: '1',
      author: 'Sarah M.',
      rating: 5,
      content: 'An absolute masterpiece...',
      date: '2024-01-15',
    },
    {
      id: '2',
      author: 'Sarah M.',
      rating: 5,
      content: 'An absolute masterpiece...',
      date: '2024-01-15',
    },
    {
      id: '3',
      author: 'Sarah M.',
      rating: 5,
      content: 'An absolute masterpiece...',
      date: '2024-01-15',
    },
  ],
  tags: [
    { name: 'magic', count: 245 },
    { name: 'wizards', count: 198 },
  ],

  // ✅ ДОБАВЛЕНЫ РЕКОМЕНДАЦИИ
  recommendedBooks: [
    {
      id: '2',
      title: 'Harry Potter and the Chamber of Secrets',
      author: 'J.K. Rowling',
      coverUrl: '/book2.png',
      rating: 4.6,
      ratingsCount: 114567,
      publishYear: '1998',
      price: 1299,
      discountPrice: 999,
    },
    {
      id: '3',
      title: 'Harry Potter and the Prisoner of Azkaban',
      author: 'J.K. Rowling',
      coverUrl: '/book3.png',
      rating: 4.7,
      ratingsCount: 108432,
      publishYear: '1999',
      price: 1399,
    },
    {
      id: '4',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      coverUrl: '/book4.png',
      rating: 4.8,
      ratingsCount: 98765,
      publishYear: '1937',
      price: 1199,
      discountPrice: 899,
    },
    {
      id: '5',
      title: 'The Chronicles of Narnia',
      author: 'C.S. Lewis',
      coverUrl: '/book5.png',
      rating: 4.4,
      ratingsCount: 87654,
      publishYear: '1950',
      price: 1499,
    },
    {
      id: '6',
      title: 'Percy Jackson & The Olympians: The Lightning Thief',
      author: 'Rick Riordan',
      coverUrl: '/book6.png',
      rating: 4.3,
      ratingsCount: 76543,
      publishYear: '2005',
      price: 1099,
      discountPrice: 799,
    },
    {
      id: '7',
      title: 'The Lord of the Rings: The Fellowship of the Ring',
      author: 'J.R.R. Tolkien',
      coverUrl: '/book7.png',
      rating: 4.9,
      ratingsCount: 156789,
      publishYear: '1954',
      price: 1599,
    },
  ],

  // ✅ ДОПОЛНИТЕЛЬНО: книги того же автора
  sameAuthorBooks: [
    {
      id: '2',
      title: 'Harry Potter and the Chamber of Secrets',
      author: 'J.K. Rowling',
      coverUrl: '/book2.png',
      rating: 4.6,
      ratingsCount: 114567,
      publishYear: '1998',
    },
    {
      id: '3',
      title: 'Harry Potter and the Prisoner of Azkaban',
      author: 'J.K. Rowling',
      coverUrl: '/book3.png',
      rating: 4.7,
      ratingsCount: 108432,
      publishYear: '1999',
    },
    {
      id: '8',
      title: 'The Casual Vacancy',
      author: 'J.K. Rowling',
      coverUrl: '/book8.png',
      rating: 3.8,
      ratingsCount: 23456,
      publishYear: '2012',
    },
  ],

  // ✅ ДОПОЛНИТЕЛЬНО: похожие книги по жанру
  similarGenreBooks: [
    {
      id: '4',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      coverUrl: '/book4.png',
      rating: 4.8,
      ratingsCount: 98765,
      publishYear: '1937',
    },
    {
      id: '5',
      title: 'The Chronicles of Narnia',
      author: 'C.S. Lewis',
      coverUrl: '/book5.png',
      rating: 4.4,
      ratingsCount: 87654,
      publishYear: '1950',
    },
    {
      id: '9',
      title: 'A Wrinkle in Time',
      author: "Madeleine L'Engle",
      coverUrl: '/book9.png',
      rating: 4.2,
      ratingsCount: 54321,
      publishYear: '1962',
    },
  ],
}
