export const heroSectionHeight = 400

export const bookData = {
  title: 'Гарри Поттер и философский камень',
  author: 'Дж. К. Роулинг',
  coverUrl: '/book.png',
  publishYear: '1997',
  rating: 4.5,
  ratingsCount: 126543,
  description: 'Гарри Поттер никогда даже не слышал о Хогвартсе...',
  quantity: 15,
  subjects: [
    'Фэнтези',
    'Для молодежи',
    'Магия',
    'Приключения',
    'Школа',
    'Дружба',
  ],
  details: {
    isbn: ['9780747532699', '0747532699'],
    publisher: 'Bloomsbury Publishing',
    publishDate: '26 июня 1997',
    pages: 223,
    language: 'Английский',
    format: 'Твердый переплет',
    weight: '340г',
    dimensions: '19.6 x 12.8 x 2.2 см',
  },
  authorBio: 'Дж. К. Роулинг - автор семи книг о Гарри Поттере...',
  reviews: [
    {
      id: '1',
      author: 'Сара М.',
      rating: 5,
      content: 'Абсолютный шедевр...',
      date: '2024-01-15',
    },
    {
      id: '2',
      author: 'Сара М.',
      rating: 5,
      content: 'Абсолютный шедевр...',
      date: '2024-01-15',
    },
    {
      id: '3',
      author: 'Сара М.',
      rating: 5,
      content: 'Абсолютный шедевр...',
      date: '2024-01-15',
    },
  ],
  tags: [
    { name: 'магия', count: 245 },
    { name: 'волшебники', count: 198 },
  ],
  recommendedBooks: [
    {
      id: '2',
      title: 'Гарри Поттер и Тайная комната',
      author: 'Дж. К. Роулинг',
      coverUrl: '/book2.png',
      rating: 4.6,
      ratingsCount: 114567,
      publishYear: '1998',
      price: 1299,
      discountPrice: 999,
      quantity: 8,
    },
    {
      id: '3',
      title: 'Гарри Поттер и узник Азкабана',
      author: 'Дж. К. Роулинг',
      coverUrl: '/book3.png',
      rating: 4.7,
      ratingsCount: 108432,
      publishYear: '1999',
      price: 1399,
      quantity: 12,
    },
    {
      id: '4',
      title: 'Хоббит',
      author: 'Дж. Р. Р. Толкин',
      coverUrl: '/book4.png',
      rating: 4.8,
      ratingsCount: 98765,
      publishYear: '1937',
      price: 1199,
      discountPrice: 899,
      quantity: 5,
    },
    {
      id: '5',
      title: 'Хроники Нарнии',
      author: 'К. С. Льюис',
      coverUrl: '/book5.png',
      rating: 4.4,
      ratingsCount: 87654,
      publishYear: '1950',
      price: 1499,
      quantity: 20,
    },
    {
      id: '6',
      title: 'Перси Джексон и Похититель молний',
      author: 'Рик Риордан',
      coverUrl: '/book6.png',
      rating: 4.3,
      ratingsCount: 76543,
      publishYear: '2005',
      price: 1099,
      discountPrice: 799,
      quantity: 3,
    },
    {
      id: '7',
      title: 'Властелин Колец: Братство Кольца',
      author: 'Дж. Р. Р. Толкин',
      coverUrl: '/book7.png',
      rating: 4.9,
      ratingsCount: 156789,
      publishYear: '1954',
      price: 1599,
      quantity: 7,
    },
  ],
  sameAuthorBooks: [
    {
      id: '2',
      title: 'Гарри Поттер и Тайная комната',
      author: 'Дж. К. Роулинг',
      coverUrl: '/book2.png',
      rating: 4.6,
      ratingsCount: 114567,
      publishYear: '1998',
      quantity: 8,
    },
    {
      id: '3',
      title: 'Гарри Поттер и узник Азкабана',
      author: 'Дж. К. Роулинг',
      coverUrl: '/book3.png',
      rating: 4.7,
      ratingsCount: 108432,
      publishYear: '1999',
      quantity: 12,
    },
    {
      id: '8',
      title: 'Случайная вакансия',
      author: 'Дж. К. Роулинг',
      coverUrl: '/book8.png',
      rating: 3.8,
      ratingsCount: 23456,
      publishYear: '2012',
      quantity: 4,
    },
  ],
  similarGenreBooks: [
    {
      id: '4',
      title: 'Хоббит',
      author: 'Дж. Р. Р. Толкин',
      coverUrl: '/book4.png',
      rating: 4.8,
      ratingsCount: 98765,
      publishYear: '1937',
      quantity: 5,
    },
    {
      id: '5',
      title: 'Хроники Нарнии',
      author: 'К. С. Льюис',
      coverUrl: '/book5.png',
      rating: 4.4,
      ratingsCount: 87654,
      publishYear: '1950',
      quantity: 20,
    },
    {
      id: '9',
      title: 'Излом времени',
      author: "Мадлен Л'Энгл",
      coverUrl: '/book9.png',
      rating: 4.2,
      ratingsCount: 54321,
      publishYear: '1962',
      quantity: 6,
    },
    {
      id: '10',
      title: 'Северное сияние',
      author: 'Филип Пулман',
      coverUrl: '/book10.png',
      rating: 4.1,
      ratingsCount: 43210,
      publishYear: '1995',
      quantity: 11,
    },
  ],
}
