import { Book } from '@entities/book/model/type'

export const HERO_SECTION_HEIGHT = 400
export const bookData: Book = {
  id: '1',
  title: 'Гарри Поттер и философский камень',
  author: 'Дж. К. Роулинг',
  coverUrl: '/book.png',
  publishYear: '1997',
  ratingsCount: 126543,
  description: 'Гарри Поттер никогда даже не слышал о Хогвартсе...',
  availableQuantity: 15,
  subjects: [
    'Фэнтези',
    'Для молодежи',
    'Магия',
    'Приключения',
    'Школа',
    'Дружба',
  ],
  details: {
    isbn: ['9780747532699', '0747532699'],
    publisher: 'Bloomsbury Publishing',
    publishDate: '26 июня 1997',
    pages: 223,
    language: 'Английский',
    format: 'Твердый переплет',
    weight: '340г',
    dimensions: '19.6 x 12.8 x 2.2 см',
  },
  authorBio: 'Дж. К. Роулинг — автор семи книг о Гарри Поттере...',
  reviews: [
    {
      id: '1',
      author: 'Сара М.',
      content: 'Абсолютный шедевр...',
      date: '2024-01-15',
    },
    {
      id: '2',
      author: 'Иван П.',
      content: 'Очень атмосферно, перечитывал несколько раз!',
      date: '2024-02-10',
    },
    {
      id: '3',
      author: 'Ольга К.',
      content: 'Лучшая книга детства!',
      date: '2024-03-05',
    },
  ],
  tags: [
    { name: 'магия', count: 245 },
    { name: 'волшебники', count: 198 },
    { name: 'приключения', count: 310 },
  ],
  recommendedBooks: [
    {
      id: '2',
      title: 'Гарри Поттер и Тайная комната',
      author: 'Дж. К. Роулинг',
      coverUrl: '/book2.png',
      rating: 4.6,
      ratingsCount: 114567,
      publishYear: '1998',
      price: 1299,
      discountPrice: 999,
      availableQuantity: 8,
    },
    {
      id: '3',
      title: 'Гарри Поттер и узник Азкабана',
      author: 'Дж. К. Роулинг',
      coverUrl: '/book3.png',
      rating: 4.7,
      ratingsCount: 108432,
      publishYear: '1999',
      price: 1399,
      availableQuantity: 12,
    },
    {
      id: '4',
      title: 'Хоббит',
      author: 'Дж. Р. Р. Толкин',
      coverUrl: '/book4.png',
      rating: 4.8,
      ratingsCount: 98765,
      publishYear: '1937',
      price: 1199,
      discountPrice: 899,
      availableQuantity: 5,
    },
    {
      id: '5',
      title: 'Хроники Нарнии',
      author: 'К. С. Льюис',
      coverUrl: '/book5.png',
      rating: 4.4,
      ratingsCount: 87654,
      publishYear: '1950',
      price: 1499,
      availableQuantity: 20,
    },
    {
      id: '6',
      title: 'Перси Джексон и Похититель молний',
      author: 'Рик Риордан',
      coverUrl: '/book6.png',
      rating: 4.3,
      ratingsCount: 76543,
      publishYear: '2005',
      price: 1099,
      discountPrice: 799,
      availableQuantity: 3,
    },
    {
      id: '7',
      title: 'Властелин Колец: Братство Кольца',
      author: 'Дж. Р. Р. Толкин',
      coverUrl: '/book7.png',
      rating: 4.9,
      ratingsCount: 156789,
      publishYear: '1954',
      price: 1599,
      availableQuantity: 7,
    },
  ],
}
