export const CART_ITEMS = [
  {
    id: '1',
    title: '1984',
    author: 'Джордж Оруэлл',
    price: 599,
    quantity: 1,
    availableQuantity: 5,
    coverUrl: '/book.png',
  },
  {
    id: '2',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '3',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '4',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '5',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '6',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '7',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '8',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '9',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '10',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
  {
    id: '11',
    title: 'Мастер и Маргарита',
    author: 'М. Булгаков',
    price: 799,
    quantity: 2,
    availableQuantity: 12,
    coverUrl: '/book.png',
  },
]
