import { BookData } from '@pages/book/type'

export const booksMock: BookData[] = [
  {
    id: '1',
    title: 'Гарри Поттер и философский камень',
    author: 'Дж. К. Роулинг',
    coverUrl: '/book.png',
    publishYear: '1997',
    ratingsCount: 126543,
    description: 'Первый роман о мальчике, который выжил.',
    availableQuantity: 15,
    subjects: ['Фэнтези', 'Магия', 'Приключения'],
    details: {
      isbn: ['9780747532699'],
      publisher: 'Bloomsbury Publishing',
      publishDate: '26 июня 1997',
      pages: 223,
      language: 'Английский',
      format: 'Твердый переплет',
      weight: '340г',
      dimensions: '19.6 x 12.8 x 2.2 см',
    },
    authorBio:
      'Дж. К. Роулинг — британская писательница, автор серии о Гарри Поттере.',
    reviews: [],
    tags: [
      { name: 'магия', count: 245 },
      { name: 'приключения', count: 198 },
    ],
    recommendedBooks: [],
  },
  {
    id: '2',
    title: 'Хоббит',
    author: 'Дж. Р. Р. Толкин',
    coverUrl: '/book4.png',
    publishYear: '1937',
    ratingsCount: 98765,
    description: 'История путешествия Бильбо Бэггинса к Одинокой горе.',
    availableQuantity: 5,
    subjects: ['Фэнтези', 'Драконы', 'Путешествия'],
    details: {
      isbn: ['9780007458424'],
      publisher: 'HarperCollins',
      publishDate: '21 сентября 1937',
      pages: 310,
      language: 'Английский',
      format: 'Твердый переплет',
      weight: '420г',
      dimensions: '20 x 13 x 2.5 см',
    },
    authorBio: 'Дж. Р. Р. Толкин — английский писатель и профессор Оксфорда.',
    reviews: [],
    tags: [
      { name: 'фэнтези', count: 180 },
      { name: 'драконы', count: 95 },
    ],
    recommendedBooks: [],
  },
  {
    id: '3',
    title: 'Хроники Нарнии: Лев, Колдунья и Платяной шкаф',
    author: 'К. С. Льюис',
    coverUrl: '/book5.png',
    publishYear: '1950',
    ratingsCount: 87654,
    description: 'История детей, попавших в волшебный мир Нарнии.',
    availableQuantity: 10,
    subjects: ['Фэнтези', 'Дети', 'Добро и зло'],
    details: {
      isbn: ['9780064471046'],
      publisher: 'HarperCollins',
      publishDate: '16 октября 1950',
      pages: 208,
      language: 'Английский',
      format: 'Мягкая обложка',
      weight: '250г',
      dimensions: '19 x 12.5 x 2 см',
    },
    authorBio:
      'К. С. Льюис — британский писатель, автор цикла "Хроники Нарнии".',
    reviews: [],
    tags: [
      { name: 'добро', count: 150 },
      { name: 'волшебство', count: 200 },
    ],
    recommendedBooks: [],
  },
]
