// constants.ts
export const genres = [
  { value: 'novel', label: 'Роман' },
  { value: 'story', label: 'Повесть' },
  { value: 'short_story', label: 'Рассказ' },
  { value: 'satire', label: 'Сатира' },
  { value: 'mystic', label: 'Мистика' },
  { value: 'psychological', label: 'Психологическая проза' },
  { value: 'historical', label: 'Историческая проза' },
  { value: 'classic', label: 'Классика' },
  { value: 'drama', label: 'Драма' },
  { value: 'adventure', label: 'Приключения' },
  { value: 'poetry', label: 'Поэзия' },
  { value: 'children', label: 'Детская литература' },
  { value: 'horror', label: 'Ужасы' },
  { value: 'fantasy', label: 'Фэнтези' },
  { value: 'sci_fi', label: 'Научная фантастика' },
]

export const authorsData = [
  {
    firstName: 'Фёдор',
    lastName: 'Достоевский',
    dateOfBirth: new Date('1821-11-11'),
  },
  {
    firstName: 'Лев',
    lastName: 'Толстой',
    dateOfBirth: new Date('1828-09-09'),
  },
  {
    firstName: 'Александр',
    lastName: 'Пушкин',
    dateOfBirth: new Date('1799-06-06'),
  },
  {
    firstName: 'Михаил',
    lastName: 'Булгаков',
    dateOfBirth: new Date('1891-05-15'),
  },
]

export const booksData = [
  // ========== ДОСТОЕВСКИЙ (authorIndex: 0) ==========
  {
    title: 'Преступление и наказание',
    authorIndex: 0,
    genreValue: 'psychological',
    description:
      'Психологический роман о моральном выборе студента Раскольникова.',
    publisher: 'Эксмо',
    pageCount: 671,
    language: 'ru',
    availableQuantity: 7,
    subjects: ['русская классика', 'психология', 'мораль'],
    publishedDate: new Date('1866-01-01'),
  },
  {
    title: 'Идиот',
    authorIndex: 0,
    genreValue: 'psychological',
    description:
      'История чистого и наивного князя Мышкина и его трагедии в обществе.',
    publisher: 'Эксмо',
    pageCount: 640,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['русская классика', 'философия', 'драма'],
    publishedDate: new Date('1869-01-01'),
  },
  {
    title: 'Братья Карамазовы',
    authorIndex: 0,
    genreValue: 'novel',
    description: 'Философская эпопея о семейных и нравственных конфликтах.',
    publisher: 'Эксмо',
    pageCount: 824,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['религия', 'мораль', 'философия'],
    publishedDate: new Date('1880-01-01'),
  },
  {
    title: 'Записки из подполья',
    authorIndex: 0,
    genreValue: 'short_story',
    description:
      'Ключевой текст экзистенциальной прозы — монолог человека из подполья.',
    publisher: 'Эксмо',
    pageCount: 128,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['экзистенция', 'философия'],
    publishedDate: new Date('1864-01-01'),
  },
  {
    title: 'Бесы',
    authorIndex: 0,
    genreValue: 'novel',
    description:
      'Политико-философская драма о революционных движениях и их последствиях.',
    publisher: 'Эксмо',
    pageCount: 768,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['политика', 'идеология', 'русская классика'],
    publishedDate: new Date('1872-01-01'),
  },
  {
    title: 'Игрок',
    authorIndex: 0,
    genreValue: 'novel',
    description: 'Рассказ о пагубной зависимости и человеческой страсти.',
    publisher: 'Эксмо',
    pageCount: 224,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['зависимость', 'психология'],
    publishedDate: new Date('1866-01-01'),
  },
  {
    title: 'Белые ночи',
    authorIndex: 0,
    genreValue: 'short_story',
    description:
      'Лирическая повесть о короткой романтической встрече ночного мечтателя.',
    publisher: 'Эксмо',
    pageCount: 56,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['любовь', 'лирика'],
    publishedDate: new Date('1848-01-01'),
  },
  {
    title: 'Униженные и оскорблённые',
    authorIndex: 0,
    genreValue: 'novel',
    description:
      'Рассказ о судьбах людей, попавших в тяжёлые жизненные обстоятельства.',
    publisher: 'Эксмо',
    pageCount: 352,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['социальная проза', 'драма'],
    publishedDate: new Date('1861-01-01'),
  },
  {
    title: 'Вечный муж',
    authorIndex: 0,
    genreValue: 'short_story',
    description:
      'Краткая повесть о сложных отношениях и ревности между мужчинами.',
    publisher: 'Эксмо',
    pageCount: 120,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['психология', 'драма'],
    publishedDate: new Date('1870-01-01'),
  },
  {
    title: 'Записки из мёртвого дома',
    authorIndex: 0,
    genreValue: 'novel',
    description: 'Опыты и наблюдения заключённого в сибирской каторге.',
    publisher: 'Эксмо',
    pageCount: 300,
    language: 'ru',
    availableQuantity: 3,
    subjects: ['каторга', 'социальная проза'],
    publishedDate: new Date('1861-01-01'),
  },
  {
    title: 'Двойник',
    authorIndex: 0,
    genreValue: 'short_story',
    description: 'Рассказ о раздвоении личности и социальном давлении.',
    publisher: 'Эксмо',
    pageCount: 96,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['психология', 'сатира'],
    publishedDate: new Date('1846-01-01'),
  },
  {
    title: 'Игрушка для взрослых (неполная подборка)',
    authorIndex: 0,
    genreValue: 'short_story',
    description: 'Сборник коротких произведений и заметок.',
    publisher: 'Эксмо',
    pageCount: 112,
    language: 'ru',
    availableQuantity: 3,
    subjects: ['сборник', 'классика'],
    publishedDate: new Date('1870-01-01'),
  },

  // ========== ТОЛСТОЙ (authorIndex: 1) ==========
  {
    title: 'Война и мир',
    authorIndex: 1,
    genreValue: 'historical',
    description: 'Эпическая хроника России в эпоху наполеоновских войн.',
    publisher: 'Эксмо',
    pageCount: 1225,
    language: 'ru',
    availableQuantity: 7,
    subjects: ['история', 'эпопея', 'русская классика'],
    publishedDate: new Date('1869-01-01'),
  },
  {
    title: 'Анна Каренина',
    authorIndex: 1,
    genreValue: 'novel',
    description:
      'Трагическая история любви и общественной морали в России XIX века.',
    publisher: 'Эксмо',
    pageCount: 864,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['любовь', 'общество', 'драма'],
    publishedDate: new Date('1877-01-01'),
  },
  {
    title: 'Смерть Ивана Ильича',
    authorIndex: 1,
    genreValue: 'short_story',
    description:
      'Повествование о смысле жизни и смерти чиновника Иванa Ильича.',
    publisher: 'Эксмо',
    pageCount: 112,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['философия', 'жизнь и смерть'],
    publishedDate: new Date('1886-01-01'),
  },
  {
    title: 'Хаджи-Мурат',
    authorIndex: 1,
    genreValue: 'novel',
    description: 'История горского вождя и конфликтов на Кавказе.',
    publisher: 'Эксмо',
    pageCount: 240,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['история', 'приключения'],
    publishedDate: new Date('1912-01-01'),
  },
  {
    title: 'Казаки',
    authorIndex: 1,
    genreValue: 'novel',
    description: 'Рассказ о жизни казаков и столкновениях культуры и морали.',
    publisher: 'Эксмо',
    pageCount: 160,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['этнография', 'социальная проза'],
    publishedDate: new Date('1863-01-01'),
  },
  {
    title: 'Севастопольские рассказы',
    authorIndex: 1,
    genreValue: 'short_story',
    description: 'Наблюдения и рассказы с поля боя в Крымской войне.',
    publisher: 'Эксмо',
    pageCount: 200,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['война', 'репортаж'],
    publishedDate: new Date('1855-01-01'),
  },
  {
    title: 'Детство. Отрочество. Юность',
    authorIndex: 1,
    genreValue: 'story',
    description: 'Три связанных повести о взрослении и формировании личности.',
    publisher: 'Эксмо',
    pageCount: 400,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['воспитание', 'биография'],
    publishedDate: new Date('1852-01-01'),
  },
  {
    title: 'Воскресение',
    authorIndex: 1,
    genreValue: 'novel',
    description: 'Роман о нравственном прозрении и социальной справедливости.',
    publisher: 'Эксмо',
    pageCount: 600,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['правосудие', 'справедливость'],
    publishedDate: new Date('1899-01-01'),
  },
  {
    title: 'Семейное счастье',
    authorIndex: 1,
    genreValue: 'novel',
    description: 'История семейной жизни и духовного роста героя.',
    publisher: 'Эксмо',
    pageCount: 220,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['семья', 'любовь'],
    publishedDate: new Date('1859-01-01'),
  },
  {
    title: 'Полное собрание рассказов (выборка)',
    authorIndex: 1,
    genreValue: 'short_story',
    description: 'Набор рассказов и этюдов Толстого.',
    publisher: 'Эксмо',
    pageCount: 320,
    language: 'ru',
    availableQuantity: 3,
    subjects: ['сборник', 'классика'],
    publishedDate: new Date('1860-01-01'),
  },
  {
    title: 'Война и мир. Краткий курс (адаптация)',
    authorIndex: 1,
    genreValue: 'historical',
    description: 'Краткая адаптация эпопеи для широкого круга читателей.',
    publisher: 'Эксмо',
    pageCount: 280,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['адаптация', 'история'],
    publishedDate: new Date('2001-01-01'),
  },
  {
    title: 'Рассказ о том, как один мужик двух генералов прокормил',
    authorIndex: 1,
    genreValue: 'short_story',
    description: 'Короткая сатирическая история на тему власти и бюрократии.',
    publisher: 'Эксмо',
    pageCount: 56,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['сатира', 'общество'],
    publishedDate: new Date('1885-01-01'),
  },

  // ========== ПУШКИН (authorIndex: 2) ==========
  {
    title: 'Евгений Онегин',
    authorIndex: 2,
    genreValue: 'poetry',
    description: 'Роман в стихах о любви, судьбе и русской жизни.',
    publisher: 'Эксмо',
    pageCount: 432,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['поэзия', 'роман', 'классика'],
    publishedDate: new Date('1833-01-01'),
  },
  {
    title: 'Капитанская дочка',
    authorIndex: 2,
    genreValue: 'novel',
    description: 'Историческая повесть о восстании Пугачёва и судьбах людей.',
    publisher: 'Эксмо',
    pageCount: 256,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['история', 'приключения'],
    publishedDate: new Date('1836-01-01'),
  },
  {
    title: 'Пиковая дама',
    authorIndex: 2,
    genreValue: 'short_story',
    description: 'Повесть о карточной страсти и судьбе молодого офицера.',
    publisher: 'Эксмо',
    pageCount: 96,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['мистика', 'судьба'],
    publishedDate: new Date('1834-01-01'),
  },
  {
    title: 'Дубровский',
    authorIndex: 2,
    genreValue: 'novel',
    description: 'Повесть о дворянстве, несправедливости и мщении.',
    publisher: 'Эксмо',
    pageCount: 224,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['приключения', 'классика'],
    publishedDate: new Date('1841-01-01'),
  },
  {
    title: 'Медный всадник',
    authorIndex: 2,
    genreValue: 'poetry',
    description: 'Лирическое стихотворение о Петербурге и судьбе человека.',
    publisher: 'Эксмо',
    pageCount: 48,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['поэзия', 'город'],
    publishedDate: new Date('1833-01-01'),
  },
  {
    title: 'Повести покойного Ивана Петровича Белкина',
    authorIndex: 2,
    genreValue: 'short_story',
    description: 'Сборник небольших повестей с разными сюжетами и характерами.',
    publisher: 'Эксмо',
    pageCount: 176,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['сборник', 'повесть'],
    publishedDate: new Date('1831-01-01'),
  },
  {
    title: 'Борис Годунов',
    authorIndex: 2,
    genreValue: 'drama',
    description: 'Трагедия о власти, предательстве и исторических событиях.',
    publisher: 'Эксмо',
    pageCount: 160,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['драма', 'история'],
    publishedDate: new Date('1825-01-01'),
  },
  {
    title: 'Цыганы',
    authorIndex: 2,
    genreValue: 'short_story',
    description: 'Рассказ о любви и свободе в жизни цыганского племени.',
    publisher: 'Эксмо',
    pageCount: 64,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['любовь', 'приключения'],
    publishedDate: new Date('1827-01-01'),
  },
  {
    title: 'Маленькие трагедии',
    authorIndex: 2,
    genreValue: 'drama',
    description: 'Небольшие драматические пьесы, затрагивающие вечные темы.',
    publisher: 'Эксмо',
    pageCount: 112,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['драма', 'пьеса'],
    publishedDate: new Date('1830-01-01'),
  },
  {
    title: 'Арап Петра Великого',
    authorIndex: 2,
    genreValue: 'short_story',
    description: 'Повествование о судьбе человека времён Петра Великого.',
    publisher: 'Эксмо',
    pageCount: 76,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['история', 'повесть'],
    publishedDate: new Date('1836-01-01'),
  },
  {
    title: 'Повести и рассказы (сборник)',
    authorIndex: 2,
    genreValue: 'short_story',
    description: 'Выборка коротких произведений Пушкина.',
    publisher: 'Эксмо',
    pageCount: 200,
    language: 'ru',
    availableQuantity: 3,
    subjects: ['сборник', 'поэзия'],
    publishedDate: new Date('1840-01-01'),
  },
  {
    title: 'Книга «Пушкин в прозе» (выборка)',
    authorIndex: 2,
    genreValue: 'short_story',
    description: 'Адаптированные прозовые произведения.',
    publisher: 'Эксмо',
    pageCount: 160,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['адаптация', 'классика'],
    publishedDate: new Date('2005-01-01'),
  },

  // ========== БУЛГАКОВ (authorIndex: 3) ==========
  {
    title: 'Мастер и Маргарита',
    authorIndex: 3,
    genreValue: 'mystic',
    description: 'Мистика, сатира и философия в одном романе о добре и зле.',
    publisher: 'Эксмо',
    pageCount: 384,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['мистика', 'сатиры', 'философия'],
    publishedDate: new Date('1967-01-01'),
  },
  {
    title: 'Собачье сердце',
    authorIndex: 3,
    genreValue: 'satire',
    description:
      'Сатира на эксперименты над человеком и общественные преобразования.',
    publisher: 'Эксмо',
    pageCount: 160,
    language: 'ru',
    availableQuantity: 6,
    subjects: ['сатира', 'наука', 'общество'],
    publishedDate: new Date('1925-01-01'),
  },
  {
    title: 'Белая гвардия',
    authorIndex: 3,
    genreValue: 'novel',
    description:
      'Драматический роман о жизни интеллигенции в дни гражданской войны.',
    publisher: 'Эксмо',
    pageCount: 320,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['гражданская война', 'драма'],
    publishedDate: new Date('1925-01-01'),
  },
  {
    title: 'Роковые яйца',
    authorIndex: 3,
    genreValue: 'sci_fi',
    description:
      'Фантастическая повесть о научном эксперименте, приводящем к бедствию.',
    publisher: 'Эксмо',
    pageCount: 96,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['фантастика', 'сатира'],
    publishedDate: new Date('1924-01-01'),
  },
  {
    title: 'Записки юного врача',
    authorIndex: 3,
    genreValue: 'short_story',
    description: 'Набор автобиографических зарисовок о работе молодого врача.',
    publisher: 'Эксмо',
    pageCount: 160,
    language: 'ru',
    availableQuantity: 5,
    subjects: ['медицина', 'автобиография'],
    publishedDate: new Date('1926-01-01'),
  },
  {
    title: 'Дни Турбиных',
    authorIndex: 3,
    genreValue: 'drama',
    description: 'Пьеса о судьбах семьи Турбиных во времена революции.',
    publisher: 'Эксмо',
    pageCount: 200,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['пьеса', 'история'],
    publishedDate: new Date('1926-01-01'),
  },
  {
    title: 'Морфий',
    authorIndex: 3,
    genreValue: 'short_story',
    description: 'Короткий, острый рассказ о зависимости врача от морфия.',
    publisher: 'Эксмо',
    pageCount: 40,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['наркотики', 'медицина'],
    publishedDate: new Date('1927-01-01'),
  },
  {
    title: 'Черный снег',
    authorIndex: 3,
    genreValue: 'short_story',
    description:
      'Автобиографическая сатира на мир театра и писательской жизни.',
    publisher: 'Эксмо',
    pageCount: 96,
    language: 'ru',
    availableQuantity: 3,
    subjects: ['театр', 'сатира'],
    publishedDate: new Date('1936-01-01'),
  },
  {
    title: 'Записки на манжетах (фрагменты)',
    authorIndex: 3,
    genreValue: 'short_story',
    description:
      'Короткие заметки и очерки, связанные с литературной и театральной жизнью.',
    publisher: 'Эксмо',
    pageCount: 120,
    language: 'ru',
    availableQuantity: 3,
    subjects: ['очерки', 'театра'],
    publishedDate: new Date('1928-01-01'),
  },
  {
    title: 'Театральный роман (фрагменты)',
    authorIndex: 3,
    genreValue: 'novel',
    description: 'Эпизоды из жизни советского театра и литературы.',
    publisher: 'Эксмо',
    pageCount: 280,
    language: 'ru',
    availableQuantity: 4,
    subjects: ['театр', 'социальная сатира'],
    publishedDate: new Date('1930-01-01'),
  },
  {
    title: 'Письма и дневники (выборка)',
    authorIndex: 3,
    genreValue: 'short_story',
    description: 'Сборник писем и дневниковых заметок Булгакова.',
    publisher: 'Эксмо',
    pageCount: 220,
    language: 'ru',
    availableQuantity: 3,
    subjects: ['дневники', 'автобиография'],
    publishedDate: new Date('1990-01-01'),
  },
  {
    title: 'Комедии и рассказы (сборник)',
    authorIndex: 3,
    genreValue: 'short_story',
    description:
      'Сборник коротких произведений, включающий сатирические очерки.',
    publisher: 'Эксмо',
    pageCount: 200,
    language: 'ru',
    availableQuantity: 3,
    subjects: ['сборник', 'сатира'],
    publishedDate: new Date('1935-01-01'),
  },
]

/**
 * recommendations: массив длиной booksData.length, где каждый элемент — массив
 * из индексов (1-based), указывающих на рекомендованные книги.
 * Правило: 3 других книги того же автора (если возможно).
 */
export const recommendations: number[][] = [
  // ДОСТОЕВСКИЙ (1..12)
  [2, 3, 4],
  [1, 3, 5],
  [1, 2, 6],
  [1, 5, 2],
  [3, 6, 1],
  [3, 2, 5],
  [1, 4, 3],
  [2, 9, 11],
  [7, 4, 2],
  [3, 6, 8],
  [3, 1, 2],
  [2, 4, 5],

  // ТОЛСТОЙ (13..24)
  [14, 15, 16],
  [13, 15, 17],
  [13, 14, 18],
  [13, 19, 14],
  [14, 16, 20],
  [15, 13, 21],
  [13, 22, 14],
  [16, 19, 13],
  [14, 23, 17],
  [13, 24, 15],
  [14, 18, 16],
  [13, 15, 19],

  // ПУШКИН (25..36)
  [26, 27, 28],
  [25, 27, 29],
  [25, 26, 30],
  [25, 28, 31],
  [29, 26, 27],
  [25, 27, 32],
  [25, 29, 26],
  [27, 30, 25],
  [26, 31, 28],
  [25, 33, 27],
  [26, 28, 29],
  [25, 27, 30],

  // БУЛГАКОВ (37..48)
  [38, 39, 40],
  [37, 39, 41],
  [37, 38, 42],
  [37, 40, 43],
  [39, 41, 37],
  [37, 38, 44],
  [37, 39, 45],
  [38, 40, 46],
  [37, 41, 39],
  [37, 42, 38],
  [39, 40, 37],
  [37, 38, 39],
]
